### ISSUE TITLE
Dataset extracting error

### ISSUE THREAD

**Issue by GopiRajuMatta** [jiwei0921/MVSS-Baseline#1]
Hello @jiwei0921,

Thank you for releasing very useful dataset!

I requested for the dataset and received the link. While extracting, I am getting error, can you please check it once..

Thank you
Gopi

**Comment by jiwei0921** [comment]
Hi Gopi,

Thanks for your interests in our work.

I've reviewed the dataset download link, and attempted to download and extract it once more. It worked successfully on my end (using 'tar -xvf MVSeg_Dataset.tar.gz'). Could you please try again? If you encounter any error messages, could you share them with us?

Hope it helps.

Best regards,
Wei

**Comment by GopiRajuMatta** [comment]
Hello @jiwei0921,

Thank you for your quick response. It is working, I directly tried to extract and then used a different command. With above command, it is working.

Thank you
Gopi

**Comment by changjinglu-wsh** [comment]
Hello, do you still have this dataset? Could you share it with me? I am a graduate student and need it for learning purposes. However, the author's link is no longer valid.
