### ISSUE TITLE
dataset download

### ISSUE THREAD

**Issue by Laulen** [jiwei0921/MVSS-Baseline#3]
Hello, I am a PhD candidate and I am very interested in your work. I submitted the application for access when I downloaded the dataset. I look forward to your approval.

**Comment by jiwei0921** [comment]
Thank you for your interest in our work. Your request has been approved.

**Comment by changjinglu-wsh** [comment]
Hello, do you still have this dataset? Could you share it with me? I am a graduate student and need it for learning purposes. However, the author's link is no longer valid.
